#pragma once

#define TOGGLE_SNAPPING 1157
#define TOGGLE_MUTE_ON_SELECTED_TRACKS 6
#define TOGGLE_SOLO_ON_SELECTED_TRACKS 7
#define SELECT_AND_MOVE_TO_NEXT_ITEM 40417
#define SELECT_AND_MOVE_TO_PREV_ITEM 40416
#define GO_TO_NEXT_MARKER_OR_PROJECT_END 40173
#define GO_TO_PREV_MARKER_OR_PROJECT_START 40172

#define TOGGLE_MUTE_ON_SELECTED_ITEMS 40175
#define TOGGLE_LOCK_ON_SELECTED_ITEMS 40687